const HDD_IMAGE='https://image.pngaaa.com/313/2561313-middle.png';
const WHATSAPP_NUMBER='919315170420';
const defaultProducts=[
{id:1,cat:'processor',brand:'Intel',name:'Intel Core i5-12400F Desktop Processor',specs:'6 Cores | 12 Threads | Up to 4.4GHz',price:13999,mrp:16499,rating:4.5,reviews:2300,badge:'Bestseller',icon:'🧠'},
{id:2,cat:'processor',brand:'Intel',name:'Intel Core i7-13700K Desktop Processor',specs:'16 Cores | 24 Threads | Up to 5.4GHz',price:34999,mrp:41999,rating:4.6,reviews:1200,icon:'🧠'},
{id:3,cat:'processor',brand:'AMD',name:'AMD Ryzen 5 5600X Processor',specs:'6 Cores | 12 Threads | Up to 4.6GHz',price:12499,mrp:15999,rating:4.4,reviews:3400,badge:'Bestseller',icon:'🧠'},
{id:4,cat:'gpu',brand:'NVIDIA',name:'NVIDIA GeForce RTX 4060 8GB Graphics Card',specs:'8GB GDDR6 | Ray Tracing | DLSS 3',price:28999,mrp:32999,rating:4.5,reviews:1900,badge:'Bestseller',icon:'🎮'},
{id:5,cat:'gpu',brand:'AMD',name:'AMD Radeon RX 6600 8GB Graphics Card',specs:'8GB GDDR6 | 1080p Gaming',price:19999,mrp:23999,rating:4.3,reviews:1100,icon:'🎮'},
{id:6,cat:'ram',brand:'Corsair',name:'Corsair Vengeance 16GB DDR4 3200MHz RAM',specs:'16GB | 3200MHz | CL16',price:3499,mrp:4299,rating:4.6,reviews:5200,badge:'Bestseller',icon:'💾'},
{id:7,cat:'ram',brand:'Crucial',name:'Crucial 8GB DDR4 2666MHz RAM',specs:'8GB | 2666MHz | CL19',price:1799,mrp:2299,rating:4.4,reviews:8100,icon:'💾'},
{id:8,cat:'ssd',brand:'Samsung',name:'Samsung 970 EVO Plus 1TB NVMe SSD',specs:'1TB | NVMe M.2 | Up to 3500MB/s',price:6499,mrp:8999,rating:4.8,reviews:6700,badge:'Bestseller',icon:'⚡'},
{id:9,cat:'ssd',brand:'WD',name:'WD Blue 500GB SATA Internal SSD',specs:'500GB | SATA III | Up to 560MB/s',price:2799,mrp:3499,rating:4.5,reviews:4300,icon:'⚡'},
{id:10,cat:'hdd',brand:'Seagate',name:'Seagate Barracuda 2TB Internal Hard Drive',specs:'2TB | 7200RPM | SATA III',price:4199,mrp:5199,rating:4.4,reviews:3900,icon:'🗄️',image:HDD_IMAGE},
{id:11,cat:'hdd',brand:'WD',name:'WD Elements 1TB External Hard Drive',specs:'1TB | USB 3.0 | Portable',price:3299,mrp:3999,rating:4.5,reviews:7200,badge:'Bestseller',icon:'🗄️',image:HDD_IMAGE},
{id:12,cat:'accessories',brand:'Logitech',name:'Logitech G102 Lightsync Gaming Mouse',specs:'RGB | 8000 DPI | Wired',price:899,mrp:1199,rating:4.5,reviews:12000,badge:'Bestseller',icon:'🖱️'},
{id:13,cat:'accessories',brand:'Corsair',name:'Corsair K55 RGB Gaming Keyboard',specs:'Membrane | RGB Backlit | Wired',price:3499,mrp:4499,rating:4.4,reviews:2800,icon:'⌨️'}
];
const categories=[['processor','Processor','🧠'],['gpu','Graphics Card','🎮'],['ram','RAM','💾'],['ssd','SSD','⚡'],['hdd','Hard Disk','🗄️'],['accessories','Accessories','🔌']];
let products=JSON.parse(localStorage.getItem('techniv_products')||'null')||defaultProducts;
let cart=JSON.parse(localStorage.getItem('techniv_cart')||'[]');
let wishlist=JSON.parse(localStorage.getItem('techniv_wishlist')||'[]');
let user=JSON.parse(localStorage.getItem('techniv_user')||'null');
let adminLoggedIn=sessionStorage.getItem('bytaro_admin')==='1';
let state={page:'home',cat:'all',search:'',sort:'relevance'};
const app=document.getElementById('app');
const money=n=>'₹'+Number(n).toLocaleString('en-IN');
const catName=id=>(categories.find(x=>x[0]===id)||[id,id])[1];
const iconFor=p=>p.icon||(categories.find(x=>x[0]===p.cat)||['','','📦'])[2];
const save=()=>{localStorage.setItem('techniv_products',JSON.stringify(products));localStorage.setItem('techniv_cart',JSON.stringify(cart));localStorage.setItem('techniv_wishlist',JSON.stringify(wishlist));localStorage.setItem('techniv_user',JSON.stringify(user))};
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
function go(page,extra={}){state={...state,page,...extra};render();scrollTo(0,0)}
function addCart(id){const x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});save();toast('Product cart me add ho gaya');render()}
function toggleWish(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save();render()}
function productCard(p){const off=Math.round((p.mrp-p.price)/p.mrp*100);return `<article class="product"><button class="heart" onclick="toggleWish(${p.id})">${wishlist.includes(p.id)?'❤️':'♡'}</button>${p.badge?`<span class="label">${p.badge}</span>`:''}<div class="product-img">${p.image?`<img src="${p.image}" alt="${p.name}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span style="display:none">${iconFor(p)}</span>`:iconFor(p)}</div><div class="product-body" onclick="go('product',{id:${p.id}})"><div class="product-name">${p.name}</div><div class="specs">${p.specs}</div><span class="rating">★ ${p.rating} (${Number(p.reviews).toLocaleString('en-IN')})</span><div style="margin-top:7px"><span class="price">${money(p.price)}</span><span class="mrp">${money(p.mrp)}</span><span class="off">${off}% off</span></div></div><div class="product-actions"><button class="btn primary" style="width:100%" onclick="addCart(${p.id})">🛒 Add to Cart</button></div></article>`}
function header(){return `<div class="topbar"><div class="nav"><div class="container navrow"><button class="navbtn" onclick="go('home')">☰</button><a class="logo" href="#" onclick="go('home');return false"><span class="logo-mark">T</span><span class="logo-text"><b>BYTARO</b><small>Build. Upgrade. Explore.</small></span></a><form class="search" onsubmit="event.preventDefault();doSearch()"><input id="searchInput" value="${state.search.replaceAll('"','&quot;')}" placeholder="Search Processor, GPU, RAM, SSD and more"><button>⌕</button></form><div class="navlinks"><button class="navbtn" onclick="go('wishlist')">♡ <span>Wishlist</span>${wishlist.length?`<i class="badge">${wishlist.length}</i>`:''}</button><button class="navbtn" onclick="go('cart')">🛒 <span>Cart</span>${cart.reduce((a,b)=>a+b.qty,0)?`<i class="badge">${cart.reduce((a,b)=>a+b.qty,0)}</i>`:''}</button><button class="navbtn" onclick="go(user?'profile':'auth')">👤 <span>${user?user.name.split(' ')[0]:'Login'}</span></button></div></div></div><div class="cats"><div class="container catrow"><button class="catbtn ${state.page==='home'?'active':''}" onclick="go('home')">⌂ Home</button>${categories.map(c=>`<button class="catbtn ${state.cat===c[0]?'active':''}" onclick="go('category',{cat:'${c[0]}',search:''})">${c[2]} ${c[1]}</button>`).join('')}</div></div></div>`}
function footer(){return `<footer class="footer"><div class="container footer-grid"><div><h3>BYTARO</h3><p style="font-size:12px">PC parts, storage and accessories — Build. Upgrade. Explore.</p></div><div><h4>Shop</h4><ul>${categories.slice(0,4).map(c=>`<li>${c[1]}</li>`).join('')}</ul></div><div><h4>Help</h4><ul><li>Track Order</li><li>Returns & Refunds</li><li>Shipping Info</li><li>Contact Us</li></ul></div><div><h4>Contact</h4><ul><li>📧 Vishalkumar07532@gmail.com</li><li>📱 9315170420</li><li>📍 Delhi, India</li></ul></div></div><div class="copyright">© 2026 BYTARO. All rights reserved.</div></footer>`}
function home(){const best=products.filter(p=>p.badge==='Bestseller');return `<section class="hero"><div class="container hero-inner"><div><span class="pill">✨ Great PC Parts Days</span><h1>Build Your Dream PC.<br>At Prices That Fit.</h1><p>Processors, Graphics Cards, RAM, SSDs, Hard Disks aur accessories — sab kuch ek jagah.</p><button class="btn white" onclick="go('category',{cat:'processor'})">Shop Now →</button></div><div class="hero-product-photo"><img src="${HDD_IMAGE}" alt="Hard Disk Drive"></div></div></section><section class="container section"><div class="section-title"><h2>Shop by Category</h2></div><div class="category-grid">${categories.map(c=>`<button class="category" onclick="go('category',{cat:'${c[0]}'})"><div class="ico">${c[2]}</div><b>${c[1]}</b></button>`).join('')}</div></section><section class="container section"><div class="section-title"><h2>Trending Bestsellers</h2><button class="btn ghost" onclick="go('category',{cat:'all'})">View All →</button></div><div class="products">${best.map(productCard).join('')}</div></section><section class="container section"><div class="feature-grid"><div class="feature">🚚 <div><b>Free Delivery</b><small>On orders above ₹999</small></div></div><div class="feature">🛡️ <div><b>Genuine Warranty</b><small>100% authentic products</small></div></div><div class="feature">↩️ <div><b>Easy Returns</b><small>7-day replacement policy</small></div></div></div></section>`}
function category(){let list=products.filter(p=>state.cat==='all'||p.cat===state.cat);if(state.search)list=list.filter(p=>(p.name+' '+p.brand+' '+catName(p.cat)).toLowerCase().includes(state.search.toLowerCase()));if(state.sort==='low')list.sort((a,b)=>a.price-b.price);if(state.sort==='high')list.sort((a,b)=>b.price-a.price);if(state.sort==='rating')list.sort((a,b)=>b.rating-a.rating);const brands=[...new Set(list.map(p=>p.brand))];return `<section class="container page"><div class="crumb">Home › ${state.search?'Search results':catName(state.cat)}</div><div class="sortbar"><h2>${state.search?`Results for "${state.search}"`:catName(state.cat)} <small style="color:#94a3b8">(${list.length})</small></h2><select class="select" onchange="state.sort=this.value;render()"><option value="relevance">Relevance</option><option value="low" ${state.sort==='low'?'selected':''}>Price Low to High</option><option value="high" ${state.sort==='high'?'selected':''}>Price High to Low</option><option value="rating" ${state.sort==='rating'?'selected':''}>Customer Rating</option></select></div><div class="layout"><aside class="panel desktop-filter"><b>Brands</b>${brands.map(b=>`<label><input type="checkbox" onchange="filterBrand(this,'${b}')"> ${b}</label>`).join('')}<hr><b>Max Price</b><input type="range" min="500" max="80000" value="80000" oninput="document.getElementById('maxv').textContent=money(this.value);filterPrice(this.value)"><span id="maxv">₹80,000</span></aside><div><div id="productGrid" class="products">${list.length?list.map(productCard).join(''):`<div class="empty" style="grid-column:1/-1">📦<br>Koi product nahi mila.</div>`}</div></div></div></section>`}
let brandFilter=[];function filterBrand(el,b){brandFilter=el.checked?[...brandFilter,b]:brandFilter.filter(x=>x!==b);render()};function filterPrice(v){document.querySelectorAll('.product').forEach(card=>{const txt=card.querySelector('.price')?.textContent.replace(/[^0-9]/g,'');card.style.display=Number(txt)<=Number(v)?'flex':'none'})}
function detail(){const p=products.find(x=>x.id===state.id);if(!p)return `<div class="container page">Product not found</div>`;const related=products.filter(x=>x.cat===p.cat&&x.id!==p.id).slice(0,4);return `<section class="container page"><div class="crumb">Home › ${catName(p.cat)} › ${p.name}</div><div class="detail"><div><div class="detail-img">${p.image?`<img src="${p.image}" alt="${p.name}" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span style="display:none">${iconFor(p)}</span>`:iconFor(p)}</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:12px"><button class="btn primary" onclick="addCart(${p.id})">🛒 Add to Cart</button><button class="btn whatsapp-btn" onclick="whatsappProduct(${p.id})">🟢 Order on WhatsApp</button></div></div><div><div style="color:#2563eb;font-size:13px">${p.brand}</div><h1>${p.name}</h1><span class="rating">★ ${p.rating} (${Number(p.reviews).toLocaleString('en-IN')})</span><div class="detail-price">${money(p.price)} <span class="mrp">${money(p.mrp)}</span></div><button class="btn ghost" onclick="toggleWish(${p.id})">${wishlist.includes(p.id)?'❤️ Saved':'♡ Add to Wishlist'}</button><div class="card" style="margin-top:18px"><b>Specifications</b><p style="font-size:13px;color:#64748b">${p.specs}</p></div><div class="feature-grid" style="margin-top:14px;grid-template-columns:repeat(3,1fr)"><div class="feature">🚚<small>Free Delivery</small></div><div class="feature">🛡️<small>1 Year Warranty</small></div><div class="feature">↩️<small>7 Day Return</small></div></div></div></div><section class="section"><h2>Similar Products</h2><div class="products">${related.map(productCard).join('')}</div></section></section>`}
function cartPage(){const items=cart.map(c=>({...c,p:products.find(p=>p.id===c.id)})).filter(x=>x.p);const subtotal=items.reduce((s,x)=>s+x.p.price*x.qty,0),mrp=items.reduce((s,x)=>s+x.p.mrp*x.qty,0),delivery=subtotal>999||!subtotal?0:99;if(!items.length)return `<div class="container empty page">🛒<h2>Cart khali hai</h2><button class="btn primary" onclick="go('home')">Continue Shopping</button></div>`;return `<section class="container page"><h2>Shopping Cart (${items.length})</h2><div class="cart-layout"><div class="card">${items.map(x=>`<div class="cart-item"><div class="mini-img">${x.p.image?`<img src="${x.p.image}" alt="${x.p.name}">`:iconFor(x.p)}</div><div style="flex:1"><b>${x.p.name}</b><p class="specs">${x.p.specs}</p><strong>${money(x.p.price)}</strong><div class="qty"><button onclick="changeQty(${x.p.id},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${x.p.id},1)">+</button></div><button class="btn ghost" style="margin-top:8px;padding:5px 8px" onclick="removeCart(${x.p.id})">Remove</button></div></div>`).join('')}</div><aside class="card"><b>Price Details</b><div class="summary-row"><span>Price</span><span>${money(mrp)}</span></div><div class="summary-row" style="color:#16a34a"><span>Discount</span><span>-${money(mrp-subtotal)}</span></div><div class="summary-row"><span>Delivery</span><span>${delivery?money(delivery):'Free'}</span></div><div class="summary-row total"><span>Total</span><span>${money(subtotal+delivery)}</span></div><button class="btn whatsapp-btn whatsapp-large" style="width:100%;margin-top:12px" onclick="whatsappCart()">🟢 Order on WhatsApp</button></aside></div></section>`}
function changeQty(id,d){const x=cart.find(c=>c.id===id);if(x){x.qty+=d;if(x.qty<=0)cart=cart.filter(c=>c.id!==id)}save();render()}function removeCart(id){cart=cart.filter(c=>c.id!==id);save();render()}
function auth(){return `<div class="auth card"><h2>${user?'Profile':'Login / Register'}</h2><form onsubmit="event.preventDefault();login()"><div class="form-row"><label>Name</label><input id="loginName" class="input" placeholder="Vishal Kumar" required></div><div class="form-row"><label>Email</label><input id="loginEmail" class="input" type="email" placeholder="you@example.com" required></div><button class="btn primary" style="width:100%">Continue</button></form></div>`}
function login(){user={name:document.getElementById('loginName').value,email:document.getElementById('loginEmail').value};save();go('home');toast('Login successful')}
function profile(){return `<section class="container page"><div class="card" style="max-width:500px;margin:auto"><h2>My Profile</h2><p><b>${user?.name||''}</b><br>${user?.email||''}</p><button class="btn danger" onclick="user=null;save();go('home')">Logout</button></div></section>`}
function checkout(){const total=cart.reduce((s,c)=>{const p=products.find(x=>x.id===c.id);return s+(p?p.price*c.qty:0)},0);if(!cart.length)return `<div class="container empty page">Cart empty</div>`;return `<section class="container page"><div class="card" style="max-width:700px;margin:auto"><h2>Checkout</h2><form onsubmit="event.preventDefault();placeOrder()"><div class="form-row"><label>Full Name</label><input class="input" id="coName" required value="${user?.name||''}"></div><div class="form-row"><label>Phone</label><input class="input" id="coPhone" required></div><div class="form-row"><label>Address</label><textarea class="input" id="coAddress" required></textarea></div><div class="form-row"><label>PIN Code</label><input class="input" id="coPin" required></div><div class="card"><b>Payment</b><p><label><input type="radio" name="pay" checked> Cash on Delivery</label></p><p><label><input type="radio" name="pay"> UPI / Online Payment</label></p></div><h3>Total: ${money(total+(total>999?0:99))}</h3><button class="btn amber" style="width:100%">Place Order</button></form></div></section>`}
function placeOrder(){cart=[];save();go('home');toast('Order placed successfully!')}
function adminLogin(){return `<section class="container page"><div class="auth card admin-login"><div class="admin-lock">🔐</div><h2>Admin Access</h2><p style="color:#64748b;font-size:13px">Sirf BYTARO owner ke liye.</p><form onsubmit="event.preventDefault();checkAdminLogin()"><div class="form-row"><label>Admin ID</label><input class="input" id="adminId" autocomplete="username" required></div><div class="form-row"><label>Password</label><input class="input" id="adminPass" type="password" autocomplete="current-password" required></div><button class="btn primary" style="width:100%">Login to Product Manager</button></form></div></section>`}
function checkAdminLogin(){const id=document.getElementById('adminId').value.trim(),pass=document.getElementById('adminPass').value;if(id==='bytaro'&&pass==='Bytaro@2026'){adminLoggedIn=true;sessionStorage.setItem('bytaro_admin','1');toast('Admin login successful');go('admin')}else toast('Wrong admin ID or password')}
function admin(){if(!adminLoggedIn)return adminLogin();return `<section class="container page"><div class="admin-head"><div><h2>⚙ Product Manager</h2><p style="color:#64748b;font-size:13px">Products yahin se add/edit/delete karo. Customers ko ye panel nahi dikhta.</p></div><div><button class="btn ghost" onclick="adminLoggedIn=false;sessionStorage.removeItem('bytaro_admin');go('home')">🔒 Logout</button> <button class="btn ghost" onclick="go('home')">← Store</button></div></div><div class="admin-grid"><form class="card" onsubmit="event.preventDefault();addProduct()"><h3>＋ Add Product</h3><div class="form-row"><label>Product Name *</label><input class="input" id="pn" required></div><div class="form-row"><label>Category *</label><select class="input" id="pc">${categories.map(c=>`<option value="${c[0]}">${c[1]}</option>`).join('')}</select></div><div class="form-row"><label>Brand</label><input class="input" id="pb"></div><div class="form-row"><label>Specifications</label><input class="input" id="ps" placeholder="1TB | SATA III | 7200RPM"></div><div class="form-row"><label>Product Image URL</label><input class="input" id="pimg" placeholder="https://.../product.jpg"></div><div class="form-row"><label>Price *</label><input class="input" id="pp" type="number" required></div><div class="form-row"><label>MRP *</label><input class="input" id="pm" type="number" required></div><div class="form-row"><label>Rating</label><input class="input" id="pr" type="number" step="0.1" value="4.5"></div><div class="form-row"><label>Reviews</label><input class="input" id="prev" type="number" value="0"></div><div class="form-row"><label>Badge</label><select class="input" id="pbadge"><option value="">None</option><option>Bestseller</option><option>New</option><option>Hot Deal</option></select></div><button class="btn primary" style="width:100%">＋ Add Product</button></form><div class="card"><h3>Products (${products.length})</h3><div class="admin-list">${products.map(p=>`<div class="admin-product"><div><b>${p.name}</b><small>${catName(p.cat)} • ${money(p.price)}</small></div><button class="btn danger" style="padding:5px 9px" onclick="deleteProduct(${p.id})">Delete</button></div>`).join('')}</div></div></div></section>`}
function addProduct(){const p={id:Date.now(),name:document.getElementById('pn').value,cat:document.getElementById('pc').value,brand:document.getElementById('pb').value||'BYTARO',specs:document.getElementById('ps').value||'Genuine product',price:Number(document.getElementById('pp').value),mrp:Number(document.getElementById('pm').value),rating:Number(document.getElementById('pr').value)||4.5,reviews:Number(document.getElementById('prev').value)||0,badge:document.getElementById('pbadge').value,image:document.getElementById('pimg').value.trim()||((categories.find(c=>c[0]===document.getElementById('pc').value)||['','','📦'])[0]==='hdd'?HDD_IMAGE:''),icon:(categories.find(c=>c[0]===document.getElementById('pc').value)||['','','📦'])[2]};products.push(p);save();toast('Product added!');go('admin')}
function deleteProduct(id){products=products.filter(p=>p.id!==id);cart=cart.filter(c=>c.id!==id);wishlist=wishlist.filter(x=>x!==id);save();render()}
function whatsappText(items,name='',phone='',address=''){const lines=items.map(x=>`• ${x.p.name} × ${x.qty} — ${money(x.p.price*x.qty)}`).join('\n');const total=items.reduce((s,x)=>s+x.p.price*x.qty,0);return `Hello BYTARO,\n\nI want to order:\n${lines}\n\nTotal: ${money(total)}\n\nCustomer: ${name||'[Name]'}\nPhone: ${phone||'[Phone]'}\nAddress: ${address||'[Delivery Address]'}\n\nPlease confirm my order.`}
function openWhatsApp(message){window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`,'_blank')}
function whatsappProduct(id){const p=products.find(x=>x.id===id);if(!p)return;openWhatsApp(whatsappText([{p,qty:1}]))}
function whatsappCart(){const items=cart.map(c=>({...c,p:products.find(p=>p.id===c.id)})).filter(x=>x.p);if(!items.length)return toast('Cart khali hai');openWhatsApp(whatsappText(items))}
function doSearch(){state.search=document.getElementById('searchInput').value.trim();go('category',{cat:'all',search:state.search})}
function render(){app.innerHTML=header()+`<main>${state.page==='home'?home():state.page==='category'?category():state.page==='product'?detail():state.page==='cart'?cartPage():state.page==='wishlist'?`<section class="container page"><h2>My Wishlist (${wishlist.length})</h2><div class="products">${products.filter(p=>wishlist.includes(p.id)).map(productCard).join('')||'<div class="empty" style="grid-column:1/-1">Wishlist khali hai</div>'}</div></section>`:state.page==='auth'?auth():state.page==='profile'?profile():state.page==='checkout'?checkout():state.page==='admin'?admin():home()}</main>`+footer()}
render();
// Hidden owner access: Ctrl + Shift + A opens the admin login without showing an Admin button to customers.
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='a'){e.preventDefault();go('admin')}});
